### PR TITLE
Add Video Selector buttons for Video Options Menu GUI

### PR DESCRIPTION
**Pull request by Hazado**
This is preparation for the when we have more than 2 in-game videos.

Changes the "Trailer GUI" to have a previous and next button
Starts playing the first video in the AVI directory
Changes the Options Menu "Uru Live Intro" to use localization text
Change the Localization text to "Videos"

Trailer GUI:
image

800x600:
image

Options GUI
image

### CODE REVIEW

**Comment by Deledrius** [comment]
Will this only affect the video viewer when launched from the Options menu, or is it visible on the first-play intro screen as well?

**Comment by Hazado** [comment]
> Will this only affect the video viewer when launched from the Options menu, or is it visible on the first-play intro screen as well?

It does at the moment, need to fix that...

**Comment by Deledrius** [comment]
Since they have a black background, it would be nice to have a bit more padding around the `previous` and `explore` buttons, and a little less on the `next` button so that they appear more uniform.

**Comment by Hazado** [comment]
> Since they have a black background, it would be nice to have a bit more padding around the `previous` and `explore` buttons, and a little less on the `next` button so that they appear more uniform.

The buttons are actually all the same size

**Comment by Deledrius** [comment]
I see that.  It leaves the `next` button with unfortunate empty space, both before and after the word, whereas the others do not.

**Comment by Hazado** [comment]
Okay, the character intro video does not show any of the new buttons now

**Comment by Hazado** [comment]
> I see that. It leaves the `next` button with unfortunate empty space, both before and after the word, whereas the others do not.

Would you prefer that `next` was touching the left instead and had the black space on the right?

**Comment by Deledrius** [comment]
Transparent looks much better, I think.

**Review by Deledrius — APPROVED** [review]

**Comment by Hazado** [comment]
Had to resave all the GUI files due to loc keyring issues found when using an external client.
The options menu GUI apparently has a lot of interdepencies for other GUI files

**Pull request merged**
