### PR TITLE
Collision Fixes

### PR DESCRIPTION
**Pull request by Hoikas**
This changeset attempts to fix the majority of the toe-stubbing colliders that have existed since the bump to PhysX 2.6.4 and new issues resulting from the introduction of PhysX 4.1 in H-uru/Plasma#690.

### CODE REVIEW

**Comment by Hoikas** [comment]
@DoobesURU is kindly looking into the rocks around the city library, but otherwise, I think this is everything... that I noticed anyhow.

**Comment by DoobesURU** [comment]
Reshaped the colliders for the rocks around the library's exterior, specifically 43 objects named "RubbleBoxCol01" through "RubbleBoxCol43" in city_District_library.prp.

Hopefully going to get the rock colliders down by the ferry terminal docks very soon.

**Comment by Hoikas** [comment]
No major regressions have surfaced through testing on the PhysX 4.1 branch and in the legacy MOUL client on Minkata. Are we good to merge this, @Deledrius?

**Comment by Deledrius** [comment]
I would say so.

**Pull request merged**
