### PR TITLE
Relto Page of Veelay Tsahvahn Sky

### PR DESCRIPTION
**Pull request by Hazado**
Script assets - https://github.com/H-uru/Plasma/pull/966

GUI_District_BkBookImages.prp
[Mipmap - xYeeshaPageVeelay7.dds] Created. Graphic done by CalumTraveler. THANK YOU!
[plImageLibMod - StandardBookImageLib] Added Mipmap "xYeeshaPageVeelay7.dds" to Images

GUI_District_YeeshaPageGUI.prp
[Scene Node - GUI_YeeshaPageGUI] Added Scene Object "YeeshaPage26-VeeTsah"
[Scene Object - YeeshaPage26-VeeTsah] Created. Added Draw Interface "YeeshaPage26-VeeTsah", Coordinate Interface "YeeshaPage26-VeeTsah", Audio Interface "cSfxGUI-Glow_28". Added to Modifiers - Gui Button Mod "GUIYeeshaPageBtn26"
[Mipmap - xYeeshaPageVeelay7.dds] Created. Graphic done by CalumTraveler. THANK YOU!
[Layer - Map #733023] Created. Duplicate of "Map #733022", Texture change to Mipmap "xYeeshaPageVeelay7.dds"
[Material - sketchVeeTsah] Created. Added to Layers - Layer Animation "Map #733023_anim"
[Audio Interface - cSfxGUI-Glow_28] Duplicate of Audio Interface "cSfxGUI-Glow_27", Audible set to Win Audible "cSfxGUI-Glow_28", Owner set to Scene Object "YeeshaPage26-VeeTsah"
[Win Audible - cSfxGUI-Glow_28] Duplicate of Win Audible "cSfxGUI-Glow_27", Sound Object set to Static Sound "cSfxGUI-Glow_Win32GUISound27"
[Coordinate Interface - YeeshaPagePlane] Children - Added Scene Object "YeeshaPage26-VeeTsah"
[Coordinate Interface - YeeshaPage26-VeeTsah] Duplicate of Coord Interface "YeeshaPage25-BahroPoles". Owner changed to Scene Object "YeeshaPage26-VeeTsah".
[Draw Interface - YeeshaPage26-VeeTsah] Created. Owner set to Scene Object "YeeshaPage26-VeeTsah". Draw key set to 0 and Drawable Span "GUI_YeeshaPageGUI_10000008_0BlendSpans_Page26"
[Layer Animation - Map #733023_anim] Duplicate of Layer Animation "Map #733022_anim". Base Layer set to Layer "Map #733023"
[Drawable Span - GUI_YeeshaPageGUI_10000008_0BlendSpans_Page26] Created with Blender
[Static Sound - cSfxGUI-Glow_Win32GUISound27] Duplicate of Static Sound "cSfxGUI-Glow_Win32GUISound26"
[GUI Dialog Mod - YeeshaPageGUI] Added GUI Button Mod "GUIYeeshaPageBtn26" between "GUIYeeshaPageBtn24" and "GUICancelLB"
[GUI Button Mod - GUIYeeshaPageBtn26] Duplicate of GUIYeeshaPageBtn25. Tag ID set to 226. Animation set to Layer Animation "Map #733023_anim"

Personal_District_psnlFanYeeshaPages01.prp
New!

Personal_District_psnlMYSTII.prp
[Scene Object - Butte006Top02] Added Simulation Interface "Butte006Top02"
[Scene Object - Butte06btm02] Added Simulation Interface "Butte06btm02"
[Scene Object - SkyHigh] Added to Modifiers - Python File Mod "cPythYeeshaPage26 - VeeTsah Off"
[Scene Object - SkyLow] Added to Modifiers - Python File Mod "cPythYeeshaPage26 - VeeTsah Off"
[Simulation Interface - Butte06btm02] Created
[Simulation Interface - Butte006Top02] Created
[Generic Physical - Surface] Added Collision Mesh to hole in back of island
[Generic Physical - Butte06btm02] Created with blender
[Generic Physical - Butte006Top02] Created with blender

Personal_District_Textures.prp
[Mipmap - ALPHAGEN_NorthernSten.jpg] Added from VeeTsah_District_Textures.prp - Courtesy of Doobes
[Mipmap - BackNeb.hsm] Added from VeeTsah_District_Textures.prp - Courtesy of Doobes
[Mipmap - Horizon.dds] Added from VeeTsah_District_Textures.prp - Courtesy of Doobes
[Mipmap - Nebula.hsm] Added from VeeTsah_District_Textures.prp - Courtesy of Doobes
[Mipmap - NorthernLights02.dds] Color Alterations to better fit Relto Lighting of texture Originally from VeeTsah_District_Textures.prp - Courtesy of Doobes
[Mipmap - prsnmoon_0_0.dds] New - Altered to reduce black outline, original texture from prsnmoon*0#0.hsm
[Mipmap - Starfield3.hsm] Added from VeeTsah_District_Textures.prp - Courtesy of Doobes

Co-authored-by: DoobesURU <Ptrck10381@gmail.com>
Co-authored-by: Traveler263 <87665301+Traveler263@users.noreply.github.com>

### CODE REVIEW

**Review by Hoikas — CHANGES_REQUESTED** [review]
I would like to see all textures in Cyan PRPs use the `.hsm` extension for consistency.

[plMipmap] prsnmoon_0_0.dds
- Is this a duplicate of prsnmoon*0#0.hsm?

[plDrawableSpans] GUI_YeeshaPageGUI_10000008_0BlendSpans_Page26
- This needs to be collapsed into GUI_YeeshaPageGUI_10000008_0BlendSpans, perhaps using gpp.

**Comment by Hazado** [comment]
prsnmoon_0_0.dds is slightly changed to remove the dark outline.

I tried to collapse it in and failed miserably.

**Comment by Hoikas** [comment]
Hmm... The only thing I could see different between the two moon textures is that prsnmoon_0_0.dds seems to have some banding from being compressed in Korman? But I wasn't looking at any transparency.

**Comment by Hazado** [comment]
> Hmm... The only thing I could see different between the two moon textures is that prsnmoon_0_0.dds seems to have some banding from being compressed in Korman? But I wasn't looking at any transparency.

outline of the moon isn't as visible, I did this because I added duplicate moons with opacity set to 1, to prevent stars from shining through them. When I did that it looked like a comic book moon though.

**Comment by Hazado** [comment]
Moon Comparison shot
image

**Comment by Hoikas** [comment]
Regression: Incorrect sky with no Relto pages active

image

**Comment by Hoikas** [comment]
image

**Comment by Hoikas** [comment]
New page icon stretches the Relto imagery without regard to the source image's aspect ratio.

image

**Comment by Hoikas** [comment]
```
FindKey: Uoid objID mismatch
	Requested: (S:0xd0023 F:0 I:3 N:cPythYeeshaPage26 - VeeTsah Off C:[0,0])
	Got: (S:0xd0023 F:0 I:3 N:cPythYeeshaPage27 - Ocean On C:[0,0])
```

**Comment by Hazado** [comment]
> image
> 
> This seems to only happen when the storm page is active.

Yes, Storm page is clouds set to 50% opacity. Due to this you can see the fog line and horizon that is much further than the Storm.
Fog is different colors at night, which is the color mismatch.

**Comment by Hoikas** [comment]
IMO we need to have color consistency and no striping in the Age.

**Comment by Hazado** [comment]
> New page icon stretches the Relto imagery without regard to the source image's aspect ratio.
> 
> image

The source was too small for the area, I guess I can fix the source instead of adjusting the UV.

**Comment by Hazado** [comment]
Fixed the source and centered better in the book GUI
image

**Comment by Hoikas** [comment]
- I'd like to see one of the following happen with `prsnmoon_0_0.dds`
  - Replace `prsnmoon*0#0.hsm` with this texture and delete the ".dds" version, or
  - Rename it to something more descriptive and change the extension to ".hsm" to match the rest of the textures.
- Still need to normalize all the new textures extensions to `.hsm` like the rest of the textures. Ideally, including the same suffix PlasmaMax uses (eg `*1#0.hsm`)
- There's some questionable fringing when the storm crosses over the nebula.
image

**Comment by Hoikas** [comment]
Hmmm....

image

**Comment by Hoikas** [comment]
One more request - nuke the VeeTsah changes out of this pull request so we can handle all of that separately.

**Comment by Hoikas** [comment]
Conflicts with #71

**Comment by Hoikas** [comment]
Conflicts with #70

**Comment by Hazado** [comment]
Conflicts with PR #82

**Pull request merged**
