### PR TITLE
Remove Visitor selection from Character selection screen

### PR DESCRIPTION
**Pull request by Hazado**
Moves all the Visitor elements off screen and shrinks the space freed up from doing that

image

### CODE REVIEW

**Comment by Hoikas** [comment]
I wonder if the whole dialog needs to be verically centered now?

Before:
image

After:
image

**Comment by Hoikas** [comment]
Any progress on centering the dialog vertically?

**Comment by Hazado** [comment]
Ill do it this week

**Comment by Hazado** [comment]
Now centered
image
Diff of changes
[diff.txt](https://github.com/H-uru/moul-assets/files/8835849/diff.txt)

**Review by Hoikas — APPROVED** [review]

**Pull request merged**
