### PR TITLE
Spyroom Q4 Updates

### PR DESCRIPTION
**Pull request by DoobesURU**
Brings the spyroom 1 to 1 with the current version on MOULa.

### CODE REVIEW

**Comment by Hoikas** [comment]
Deferring until blend is also available

**Comment by Hoikas** [comment]
What's the status here? Were these PRPs deployed to MOULa?

**Comment by DoobesURU** [comment]
> What's the status here? Were these PRPs deployed to MOULa?

Yup. These are actually direct copies from MOULa. Only minor change was adding the Aussie hat. And, of course, it's now a Korman export.

**Comment by Hoikas** [comment]
OK, so we're just waiting for the blend to be added before merging, right?

**Comment by DoobesURU** [comment]
> OK, so we're just waiting for the blend to be added before merging, right?

Yep. I'll be doing that shortly in a new commit.

**Review by Hoikas — APPROVED** [review]

**Pull request merged**
