### PR TITLE
Kalamee V1 12.28.2022

### PR DESCRIPTION
**Pull request by DoobesURU**
* Adds PRP and OGG files for Age of Kalamee by Semjay and Cyan, Inc.

Note that there's a Chiso update that goes along with this (to put in a Kalamee Book), but I'll hold off on pushing that until #189 has been approved. It will be a separate PR though.

### CODE REVIEW

**Comment by Hoikas** [comment]
```
[2023-01-21 13:28:27,368] ERROR: Dependency file 'sfx/KalameeTheBeautyOfLife.ogg' (provided by: 'audio/KalameeTheBeautyOfLife.ogg') missing! Used by 'Kalamee'.
[2023-01-21 13:28:27,368] ERROR: Dependency file 'sfx/KalameeWaterfall.ogg' (provided by: 'audio/KalameeWaterfall.ogg') missing! Used by 'Kalamee'.
```

**Comment by DoobesURU** [comment]
> ```
> [2023-01-21 13:28:27,368] ERROR: Dependency file 'sfx/KalameeTheBeautyOfLife.ogg' (provided by: 'audio/KalameeTheBeautyOfLife.ogg') missing! Used by 'Kalamee'.
> [2023-01-21 13:28:27,368] ERROR: Dependency file 'sfx/KalameeWaterfall.ogg' (provided by: 'audio/KalameeWaterfall.ogg') missing! Used by 'Kalamee'.
> ```

Odd. The files are in there under the `compiled/sfx` folder in the `Files changed` list. /shrug

**Comment by Hoikas** [comment]
The file extensions are `.OGG` - they need to be `.ogg`.

**Comment by DoobesURU** [comment]
> The file extensions are `.OGG` - they need to be `.ogg`.

Oddly enough, I think it's the other way around on OU. 😝 

I'll change that with a couple of commits to remove then re-add the sounds.

**Comment by Hoikas** [comment]
The case changing from `.OGG` to `.ogg` breaks the TrollLand deployment. We need to re-do all commits so that the sound files are properly named.

**Comment by ZarothYe** [comment]
> The case changing from `.OGG` to `.ogg` breaks the TrollLand deployment. We need to re-do all commits so that the sound files are properly named.

Could Doobes edit the last commit and use a `git rename` process (as rarified mentioned in discord earlier) to fix it instead of re-doing *all* the commits? Or would there still be an issue?

**Comment by Hoikas** [comment]
```
[2023-02-11 15:20:56,271] ERROR: Dependency file 'sfx/KalameeMarker.OGG' (provided by: 'audio/KalameeMarker.OGG') missing! Used by 'Kalamee'.
[2023-02-11 15:20:56,272] ERROR: Dependency file 'sfx/KalameeTrapGate.OGG' (provided by: 'audio/KalameeTrapGate.OGG') missing! Used by 'Kalamee'.
```

The file extensions in the PRP files are probably uppercased when they should be lower cased. This results in weird garbage sounds being played in game.

**Comment by Hoikas** [comment]
Still getting this critical error https://github.com/H-uru/moul-assets/pull/199#issuecomment-1426908650

**Comment by DoobesURU** [comment]
> ```
> [2023-02-11 15:20:56,271] ERROR: Dependency file 'sfx/KalameeMarker.OGG' (provided by: 'audio/KalameeMarker.OGG') missing! Used by 'Kalamee'.
> [2023-02-11 15:20:56,272] ERROR: Dependency file 'sfx/KalameeTrapGate.OGG' (provided by: 'audio/KalameeTrapGate.OGG') missing! Used by 'Kalamee'.
> ```
> 
> The file extensions in the PRP files are probably uppercased when they should be lower cased. This results in weird garbage sounds being played in game.

Hopefully my latest couple of commits fixed this. I removed the sounds and committed that, renamed them elsewhere making sure to use .ogg lowercase, then re-added them in a second commit. Fingers crossed! 😄

**Comment by Hoikas** [comment]
Thanks for the submission. Unfortunately, at this time, we are not accepting new Ages to this repository. If you are still interested in submitting your new Age, please submit it directly to the Shard(s) that you are interested in it appearing on. Thanks!

**Pull request closed without merging**
