### PR TITLE
Wall Game fixes

### PR DESCRIPTION
**Pull request by Hazado**
Add camera responder to logic modifiers for chair clickables 
Adjust Region for panel clickables to be much larger

Diff File - [WallPhy.txt](https://github.com/H-uru/moul-assets/files/10496627/WallPhy.txt)

### CODE REVIEW

**Comment by Hazado** [comment]
Changed the conference room camera views to a load mask setup.
Ultra Graphics Quality setting shows 1024x1024 at 0.1 refresh rate
High Graphics Quality setting shows 256x256 at 0.05 refresh rate
Medium Graphics Quality setting and lower wont show the camera views at all.

Removed these light flares from the camera views inside the conference room
image

Diff Files
[walladditionsdiff.txt](https://github.com/H-uru/moul-assets/files/10609204/walladditionsdiff.txt)
[wallroomdiff.txt](https://github.com/H-uru/moul-assets/files/10609205/wallroomdiff.txt)

**Comment by Hoikas** [comment]
FWIW, your high setup will render more frequently than the ultra one. I would expect for the ultra quality image to render at basically 60fps (about 0.01), and for the high one to render less frequently eg maybe 30fps (about 0.03). You don't have to use those exact numbers, though. I expect both of those resolutions could safely be halved as well...

**Comment by dpogue** [comment]
> I expect both of those resolutions could safely be halved as well...

Just noting (because it came up previously when Hazado and I were talking about DCM resolutions): on H'uru clients, DCMs will always be rendered at the full resolution of the pipeline, regardless of the resolution provided, if pixel shaders v3 is supported.

**Comment by Hoikas** [comment]
Good point. We may want to add an escape hatch for that in the case of DCMs that aren't reflections... or have some other way of specifying it.

**Comment by Hazado** [comment]
> FWIW, your high setup will render more frequently than the ultra one. I would expect for the ultra quality image to render at basically 60fps (about 0.01), and for the high one to render less frequently eg maybe 30fps (about 0.03). You don't have to use those exact numbers, though. I expect both of those resolutions could safely be halved as well...

my intent was to reduce the load of the rendering, The wall climbing isnt exactly fast moving.

The resolutions are more for the OU client because Huru doesnt use them.

If you think the new refresh speeds wont cause issues for clients, Im fine with upping it to 60fps amd 30fps

**Comment by dpogue** [comment]
> Ultra Graphics Quality setting shows 1024x1024 at 0.1 refresh rate
> High Graphics Quality setting shows 256x256 at 0.05 refresh rate

I think what Hoikas was implying is that smaller numbers mean a higher refresh rate (shorter time between frames), so High at 0.05 is actually going to update more often that Ultra at 0.1, which is probably not what you intended?

**Comment by Hazado** [comment]
I've made the change so the Ultra runs at 60fps and High at 30fps.

**Review by Hoikas — APPROVED** [review]

**Pull request merged**
