### PR TITLE
Add Serene Particle Effects

### PR DESCRIPTION
**Pull request by DoobesURU**
Re-adds Serene's snow and bugs. Fix by Ehren.

### CODE REVIEW

**Comment by Hazado** [comment]
What version of serene was this based off of?
Was checking it against the Deep Island version.
[Particle System - GoldBugsParticles] the first 4 yaw are different on DI - 3.141590118

**Comment by Hoikas** [comment]
Could you amend these commits and set the author to `EhrenCF <EhrenCG@hotmail.com>` so that we get the attribution right?

**Comment by DoobesURU** [comment]
> 
> 
> Could you amend these commits and set the author to `EhrenCG <EhrenCG@hotmail.com>` so that we get the attribution right?

I'll try to do so on my end. Just need to figure out how with Fork.

**Comment by Hazado** [comment]
Here is a good reference on how to do it with git - https://www.educative.io/edpresso/how-to-change-a-git-commit-message-after-a-push

**Comment by DoobesURU** [comment]
> 
> 
> Here is a good reference on how to do it with git - https://www.educative.io/edpresso/how-to-change-a-git-commit-message-after-a-push

Yeah, that seems to allow me to change the title and description of a commit (as did your screenshot of Fork on Discord), but it doesn't appear to be able to change the author of said commits?

**Comment by dpogue** [comment]
> it doesn't appear to be able to change the author of said commits?

`git commit --amend --author "Name <email>"` should work

**Comment by EhrenCG** [comment]
> 
> 
> What version of serene was this based off of?
> Was checking it against the Deep Island version.
> [Particle System - GoldBugsParticles] the first 4 yaw are different on DI - 3.141590118

Looks like the compiler ignores those values, at least in this case.  Despite that though, I find that the bugs look and act the same in-game, do you disagree?

**Comment by Hazado** [comment]
Yes, I have no issues with the PR, everything works like it should.

**Comment by DoobesURU** [comment]
> 
> 
> > it doesn't appear to be able to change the author of said commits?
> 
> `git commit --amend --author "Name <email>"` should work

Tried that in the console. The thing seems to be useless as it's not doing anything no matter what/how I type it in.

**Comment by EhrenCG** [comment]
> 
> 
> > > it doesn't appear to be able to change the author of said commits?
> > 
> > 
> > `git commit --amend --author "Name <email>"` should work
> 
> Tried that in the Fork console. The thing seems to be useless as it's not doing anything no matter what/how I type it in.

I'm sort of confused by this, is there anything I'm supposed to do?

**Comment by DoobesURU** [comment]
> 
> 
> > > > it doesn't appear to be able to change the author of said commits?
> > > 
> > > 
> > > `git commit --amend --author "Name <email>"` should work
> > 
> > 
> > Tried that in the Fork console. The thing seems to be useless as it's not doing anything no matter what/how I type it in.
> 
> I'm sort of confused by this, is there anything I'm supposed to do?

Nope, just something I need to fix so you get proper credit on GitHub. ;)

**Review by Hoikas — APPROVED** [review]

**Review by Hazado — APPROVED** [review]

**Pull request merged**
