### PR TITLE
K'veer Update August 2021

### PR DESCRIPTION
**Pull request by DoobesURU**
Adds Atrus jacket, Nexus pedestal gear sfx and missing light beams in foyer.

### CODE REVIEW

**Comment by DoobesURU** [comment]
I should note that I left out the blend for now as I'm not sure how we're organizing things now with the textures in the repo. 😉

**Comment by Hoikas** [comment]
MOULa left; PR right:

- Light pedestal color different
image

- Balcony camera regression
image

**Comment by Hoikas** [comment]
Camera angle regression is still present.

**Comment by Hoikas** [comment]
What's the status on fixing the camera angle regression?

**Comment by Hoikas** [comment]
Pinging @DoobesURU for response to https://github.com/H-uru/moul-assets/pull/67#issuecomment-1048407034.

**Comment by Hoikas** [comment]
Pinging @DoobesURU for response to https://github.com/H-uru/moul-assets/pull/67#issuecomment-1048407034. I will assume this PR is abandoned if no response.

**Comment by DoobesURU** [comment]
> Pinging @DoobesURU for response to [#67 (comment)](https://github.com/H-uru/moul-assets/pull/67#issuecomment-1048407034). I will assume this PR is abandoned if no response.

Sorry about that @Hoikas. Lots of crap going on at once these days. I'll have a look at things later today when I get home. I *think* I fixed this, but need to double-check.

**Review by Hoikas — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
