### PR TITLE
Add highgarden

### PR DESCRIPTION
**Pull request by DoobesURU**
Adds the PRPs and LOC file for Tweek's Age of Fahets: Highgarden.

### CODE REVIEW

**Review by Hoikas — APPROVED** [review]

**Comment by ZarothYe** [comment]
It doesn't look like this included my suggested edits/corrections for typos and such for the LOC, possibly. It seemed like Tweek might have wanted to include those but submissions had already been frozen for OU so it didn't make it into MOULa yet. Would it make sense to include that here since there is no freeze deadline, or indeed, no requirement that the LOCs match those in OU at all?

**Comment by Hoikas** [comment]
It would be nice to have those, I think.

**Comment by DoobesURU** [comment]
> It doesn't look like this included my suggested edits/corrections for typos and such for the LOC, possibly. It seemed like Tweek might have wanted to include those but submissions had already been frozen for OU so it didn't make it into MOULa yet. Would it make sense to include that here since there is no freeze deadline, or indeed, no requirement that the LOCs match those in OU at all?

I found your changes on the Discord thread. Give me a bit of time and I'll incorporate them for a new commit.

**Review by Hoikas — APPROVED** [review]

**Comment by DoobesURU** [comment]
Shoot. It looks like I may have broken some of the CDATA bracketing on one of the elements. Please hold off on merging until I can get home later today and fix it, please!

**Comment by Hoikas** [comment]
No objections noted in a little over a week. Merging.

**Pull request merged**
