### PR TITLE
Adds the cyan camera work done to create the trailer for Myst Online

### PR DESCRIPTION
**Pull request by Hazado**
This is the cleft camera flyby done in this trailer for Myst Online
https://www.youtube.com/watch?v=rLvkMJDrMAU

Clip of how I set up to trigger the camera and the flybys
https://www.youtube.com/watch?v=8An_EP3jVfk

This PRP will never load in any game due to the age file having the page set to be controlled by page loading.
Inside the age file Line 35
`Page=trailerCamPage,18,1`
needs to be changed to load the file
`Page=trailerCamPage,18`

### CODE REVIEW

**Comment by Deledrius** [comment]
Neat!

**Comment by Hoikas** [comment]
@Deledrius Should we mainline this? I don't see any harm in taking it.

**Comment by Deledrius** [comment]
Seems like a good idea to me!

**Review by Hoikas — COMMENTED** [review]
I think that, to prevent surprises, we should remove the trigger region and instruct anyone who wants to use this to execute the console command `Logic.TriggerResponder runAnimCam` instead.

**Comment by Hoikas** [comment]
Also, the next time your tweak this, it would be nice if the `runAnimCam` responder popped the trailer camera off the camera stack when the animation ends.

**Comment by Hazado** [comment]
> I think that, to prevent surprises, we should remove the trigger region and instruct anyone who wants to use this to execute the console command `Logic.TriggerResponder runAnimCam` instead.

I added the trigger region because i couldnt figure out the commands to trigger it 😭

**Comment by Hoikas** [comment]
Send another `plCameraMsg` when the animation finishes with *only* the `kRegionPushCamera` flag set. Be sure to *not* set `kEntering` or `kResponderTrigger`.

**Comment by Hazado** [comment]
Okay, no more trigger region and regular camera is returned after animation is done.

**Review by Hoikas — APPROVED** [review]

**Pull request merged**
