### PR TITLE
Adds new clothing to Fan02 and old from CC

### PR DESCRIPTION
**Pull request by Hazado**
This allows clothing sets to work again.
Required adding Clothingset tag to description of Suit, Atrus Clothing and Catherine Clothing
Fixed a few issues with the torso icon for the Maintainer Suit
Maintainer Suit now is a clothing set, so if you equip any item of it you equip all of it

New Clothing styles by Calum Traveler
Door Runner's Fleece Jacket - Setup to award when you gather the Garden Wedges
Leather Jacket - Minkata Reward - Setup to award when you gather the Minkata Wedges
Hooded Sweatshirt - Pod Reward - Setup to award when you gather the Pod Age Wedges
Vest - Path of the Shell Reward - Setup to award when you gather the Ahnonay and Er'cana Wedges
Plain Vest - Closet Default

New Clothing by Hazado
Two tint Cargo Pants and Cargo Shorts - Closet Default

CC Clothing
Atrus Pants - Clothing Set that only worn with Atrus Shirt
Catherine Pants - Clothing Set that is only worn with Catherine Shirt
Catherine Shoes - Shoes that can be worn with anything
Deck Shoes - Closet Default item
Backpack 2 - Backpack that was found in Er'cana
Sharper Hat - Female Only (Male is already in game)

### CODE REVIEW

**Comment by Hazado** [comment]
Female02 is fixed, no duplicate mipmaps in the max or exported file.

**Comment by Hoikas** [comment]
Closes #74.

**Comment by Hoikas** [comment]
Since this is soon to make MOULa, have you included the CTour shirt from #74?

**Comment by Hazado** [comment]
> Since this is soon to make MOULa, have you included the CTour shirt from #74?

Yes, #74 is included in this

**Pull request merged**
