### PR TITLE
Great Tree Pub/Watcher's Pub Q2 2022 Update

### PR DESCRIPTION
**Pull request by DoobesURU**
As of 5-17-22:
* Adds a Nexus Book alongside the Chiso Book
* Reactivates Imager to be postable with "clue" that appears at long intervals featuring art by Tweek (requires https://github.com/H-uru/Plasma/pull/1159 for the latter)
* Ahnonay and Er'cana share ability that was erroneously left out is re-added
* Various odds and ends fixed

### CODE REVIEW

**Comment by ZarothYe** [comment]
Are there any SDL changes or anything needed to support these changes, Doobes? If not, maybe this is one we can get on TrollLand to poke at, @Hoikas ?

**Comment by DoobesURU** [comment]
> Are there any SDL changes or anything needed to support these changes, Doobes? If not, maybe this is one we can get on TrollLand to poke at, @Hoikas ?

No, no SDL changes needed. It simply requires @Hazado 's update to `xSimpleImager.py` found here: https://github.com/H-uru/Plasma/pull/1159

**Comment by Hoikas** [comment]
This was included in the last TL build.

**Comment by Hoikas** [comment]
Shouldn't the Nexus book have a DRC stamp?

**Review by Hoikas — APPROVED** [review]

**Pull request merged**
