### PR TITLE
Adds Backpack2 as a collectible in Dereno pod and correct Backpack model in Er'cana

### PR DESCRIPTION
**Pull request by Hazado**
image

### CODE REVIEW

**Review by Hoikas — APPROVED** [review]

**Comment by Hazado** [comment]
Changed the Er'cana backpack model so it matches what you get when you pick it up.
image

**Comment by Hoikas** [comment]
Just to make sure, is this PR up to date with what will be shipped to MOULa?

**Comment by Hazado** [comment]
should be but i will double check

**Comment by Hoikas** [comment]
Pinging @Hazado for response to https://github.com/H-uru/moul-assets/pull/100#issuecomment-1048407855.

**Comment by Hoikas** [comment]
Pinging @Hazado for response to https://github.com/H-uru/moul-assets/pull/100#issuecomment-1048407855. I will assume this PR is abandoned if no response.

**Comment by Hazado** [comment]
Yes this is up-to-date.

**Pull request merged**
