### PR TITLE
Enlarged the black mask of the telescope for ultra-widescreen resolutions

### PR DESCRIPTION
**Pull request by Hazado**
Before
image

After
image

### CODE REVIEW

**Review by Hoikas — APPROVED** [review]

**Comment by Deledrius** [comment]
What's the source of the image used in the new frame?

**Comment by Hazado** [comment]
Thats default image, not sure why the first doesn't have it, was taken from Cyan Chat, #moula-tech-support.
I dont have a ultra-widescreen so I just used the reported image for the before.

**Comment by Deledrius** [comment]
Ah, might be PotS vs MOULa.  I can't double-check a the moment.

**Comment by Hazado** [comment]
Ahh I see the issue, they made all the color vertex to invisible basically.
I will fix this so its the same.

**Comment by Hazado** [comment]
Not at widescreen, but here is the fixed texture
image

**Review by Hoikas — APPROVED** [review]

**Review by Deledrius — APPROVED** [review]

**Pull request merged**
