### PR TITLE
Fixes the Bahro Stone Linking Panel

### PR DESCRIPTION
**Pull request by Hazado**
Linking panel for bahro stones only have the right half of them actually usable.
This was caused by the change from the CC bahro share symbol to the Yeesha Share symbol.

### CODE REVIEW

**Comment by Hoikas** [comment]
Why not just replace the too-small mipmap?

**Comment by Hazado** [comment]
Im not sure if it is used in other places.

**Comment by Deledrius** [comment]
Can you share a before and after for the AI image here?

**Comment by Alderem** [comment]
Ideally, description should say _what about the bahro stone linking panel is being fixed_.  😅

**Comment by Hazado** [comment]
Original
image
Upscale
image

**Comment by Hoikas** [comment]
The image shouldn't be reused anywhere; let's go ahead and replace the old one.

**Comment by Hazado** [comment]
Old one replaced instead. Force pushed.

**Review by Hoikas — APPROVED** [review]
Works great, thanks for the long-needed fix!

**Comment by Deledrius** [comment]
Thanks.  The visual difference is barely discernible and produced no negative effects on the artistic aspects of the icon, so I'm happy to accept it here. :)

**Pull request merged**
