### PR TITLE
Make kickables weights more realistic

### PR DESCRIPTION
**Pull request by ZarothYe**
Depends on https://github.com/H-uru/Plasma/pull/1127.

Files changed (objects changed):
- Personal_District_psnlMYSTII.prp (KickBoulder 50 StLog 50)
- Neighborhood_District_nb01.prp done (orangecone 20 friction 2, pumpkin 7)
- Neighborhood02_District_krelKirel.prp (kirelorangecone 20 friction 2)
- Garrison_District_grsnWellFirstFloorRooms.prp (orangecone 20 friction 2, maintainerhelmet 20 maintainermark 8 mark w/ spike 14)
- Teledahn_District_tldnUpperShroom.prp (styrofoamchunk 3)
- Teledahn_District_tldnSlaveCave.prp (Basket 20, bone 30, rollingrock 50, skull 20)

I (Zaroth) could not get the Neighborhood and Neighborhood02 PRPs from the `master` branch to play nicely with the prp_as_txt.py script, so I don't have diffs for them. On the bright side, it looks like the Garrison and Teledahn PRPs had a lot of hull faces obliterated, so yay for smaller PRP files!
[GarrisonWellFirstFloorPRP_diff.txt](https://github.com/H-uru/moul-assets/files/8696209/GarrisonWellFirstFloorPRP_diff.txt)
[TeledahnUpperShroomPRP_diff.txt](https://github.com/H-uru/moul-assets/files/8696211/TeledahnUpperShroomPRP_diff.txt)
[TeledahnSlaveCavePRP_diff.txt](https://github.com/H-uru/moul-assets/files/8696213/TeledahnSlaveCavePRP_diff.txt)

(May 16th) Updated with rebased Personal PRP:

```diff --git "a/.\\PersonalPRP_curr.txt" "b/.\\PersonalPRP_new.txt"
index 09fe634..42b9752 100644
--- "a/.\\PersonalPRP_curr.txt"
+++ "b/.\\PersonalPRP_new.txt"
@@ -140181,16 +140181,16 @@ Type: plCoordinateInterface
 				<hsBitVector>kCanEverDelayTransform kDelayedTransformEval </hsBitVector>
 			</Properties>
 			<LocalToParent>
-				<hsMatrix44>[-0.965926,-0.258819,-0.000000,-2.200000 ; -0.000000,0.000000,1.000000,-3.966340 ; -0.258819,0.965926,-0.000000,2.538330 ; 0.000000,0.000000,0.000000,1.000000]</hsMatrix44>
+				<hsMatrix44>[-1.000000,0.000000,0.000000,-1.936380 ; 0.000000,0.000000,1.000000,-3.966337 ; 0.000000,1.000000,-0.000000,2.538327 ; 0.000000,0.000000,0.000000,1.000000]</hsMatrix44>
 			</LocalToParent>
 			<ParentToLocal>
-				<hsMatrix44>[-0.965926,-0.000000,-0.258819,-1.468070 ; -0.258819,0.000000,0.965926,-3.021240 ; -0.000000,1.000000,-0.000000,3.966340 ; 0.000000,0.000000,0.000000,1.000000]</hsMatrix44>
+				<hsMatrix44>[-1.000000,0.000000,0.000000,-1.936381 ; 0.000000,0.000000,1.000000,-2.538326 ; 0.000000,1.000000,-0.000000,3.966337 ; 0.000000,0.000000,0.000000,1.000000]</hsMatrix44>
 			</ParentToLocal>
 			<LocalToWorld>
-				<hsMatrix44>[-0.258819,-0.965926,-0.000000,41.047298 ; 0.965926,-0.258819,0.000000,5.923820 ; -0.000000,-0.000000,1.000000,14.236800 ; 0.000000,0.000000,0.000000,1.000000]</hsMatrix44>
+				<hsMatrix44>[-0.500000,-0.866026,0.000000,41.179150 ; 0.866026,-0.500000,0.000000,5.695517 ; 0.000000,0.000000,1.000000,14.236752 ; 0.000000,0.000000,0.000000,1.000000]</hsMatrix44>
 			</LocalToWorld>
 			<WorldToLocal>
-				<hsMatrix44>[-0.258819,0.965926,-0.000000,4.901850 ; -0.965926,-0.258819,-0.000000,41.181900 ; -0.000000,0.000000,1.000000,-14.236700 ; 0.000000,0.000000,0.000000,1.000000]</hsMatrix44>
+				<hsMatrix44>[-0.500000,0.866025,0.000000,15.657109 ; -0.866025,-0.500000,0.000000,38.509937 ; 0.000000,0.000000,1.000000,-14.236762 ; 0.000000,0.000000,0.000000,1.000000]</hsMatrix44>
 			</WorldToLocal>
 			<Children>
 			</Children>
@@ -207384,7 +207384,7 @@ Type: plGenericPhysical
 				<ExcludePersistentStates></ExcludePersistentStates>
 				<VolatileStates></VolatileStates>
 			</SyncParams>
-			<PhysicalParams Mass="3" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
+			<PhysicalParams Mass="50" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
 			<Object>
 				<plKey Name="KickBoulder" Type="plSceneObject" Location="13;1" LocFlag="0x0000" ObjID="566" />
 			</Object>
@@ -207469,7 +207469,7 @@ Type: plGenericPhysical
 				<ExcludePersistentStates></ExcludePersistentStates>
 				<VolatileStates></VolatileStates>
 			</SyncParams>
-			<PhysicalParams Mass="3" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
+			<PhysicalParams Mass="50" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
 			<Object>
 				<plKey Name="KickBoulder01" Type="plSceneObject" Location="13;1" LocFlag="0x0000" ObjID="567" />
 			</Object>
@@ -207554,7 +207554,7 @@ Type: plGenericPhysical
 				<ExcludePersistentStates></ExcludePersistentStates>
 				<VolatileStates></VolatileStates>
 			</SyncParams>
-			<PhysicalParams Mass="3" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
+			<PhysicalParams Mass="50" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
 			<Object>
 				<plKey Name="KickBoulder02" Type="plSceneObject" Location="13;1" LocFlag="0x0000" ObjID="568" />
 			</Object>
@@ -219877,7 +219877,7 @@ Type: plGenericPhysical
 				<ExcludePersistentStates></ExcludePersistentStates>
 				<VolatileStates></VolatileStates>
 			</SyncParams>
-			<PhysicalParams Mass="3" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
+			<PhysicalParams Mass="50" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
 			<Object>
 				<plKey Name="StLog23" Type="plSceneObject" Location="13;1" LocFlag="0x0000" ObjID="1154" />
 			</Object>
@@ -219958,7 +219958,7 @@ Type: plGenericPhysical
 				<ExcludePersistentStates></ExcludePersistentStates>
 				<VolatileStates></VolatileStates>
 			</SyncParams>
-			<PhysicalParams Mass="3" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
+			<PhysicalParams Mass="50" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
 			<Object>
 				<plKey Name="StLog24" Type="plSceneObject" Location="13;1" LocFlag="0x0000" ObjID="1155" />
 			</Object>
@@ -220043,7 +220043,7 @@ Type: plGenericPhysical
 				<ExcludePersistentStates></ExcludePersistentStates>
 				<VolatileStates></VolatileStates>
 			</SyncParams>
-			<PhysicalParams Mass="3" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
+			<PhysicalParams Mass="50" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
 			<Object>
 				<plKey Name="StLog25" Type="plSceneObject" Location="13;1" LocFlag="0x0000" ObjID="1156" />
 			</Object>
@@ -220123,7 +220123,7 @@ Type: plGenericPhysical
 				<ExcludePersistentStates></ExcludePersistentStates>
 				<VolatileStates></VolatileStates>
 			</SyncParams>
-			<PhysicalParams Mass="3" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
+			<PhysicalParams Mass="50" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
 			<Object>
 				<plKey Name="StLog26" Type="plSceneObject" Location="13;1" LocFlag="0x0000" ObjID="1157" />
 			</Object>
@@ -220203,7 +220203,7 @@ Type: plGenericPhysical
 				<ExcludePersistentStates></ExcludePersistentStates>
 				<VolatileStates></VolatileStates>
 			</SyncParams>
-			<PhysicalParams Mass="3" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
+			<PhysicalParams Mass="50" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
 			<Object>
 				<plKey Name="StLog27" Type="plSceneObject" Location="13;1" LocFlag="0x0000" ObjID="1158" />
 			</Object>
@@ -220282,7 +220282,7 @@ Type: plGenericPhysical
 				<ExcludePersistentStates></ExcludePersistentStates>
 				<VolatileStates></VolatileStates>
 			</SyncParams>
-			<PhysicalParams Mass="3" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
+			<PhysicalParams Mass="50" Friction="1" Restitution="0" MemberGroup="kGroupDynamic " ReportGroup="" CollideGroup="" LOSDBs="0x0000" />
 			<Object>
 				<plKey Name="StLog28" Type="plSceneObject" Location="13;1" LocFlag="0x0000" ObjID="1159" />
 			</Object>
```

### CODE REVIEW

**Comment by DamnBriggsy** [comment]
One major problem with this is no matter how I tweaked it, I could not get it such that I could stand on a cone (even with the original settings). Obviously this is an important feature of the game that needs additional investigation, but overall these weights "feel" better to me than the previous ones.

**Comment by DamnBriggsy** [comment]
I will try to fix the mentioned PRP.

These edits were not tested against OU client physx and are intended for the changes made in H-uru/Plasma#1127 only

**Comment by Hazado** [comment]
> These edits were not tested against OU client physx and are intended for the changes made in [H-uru/Plasma#1127](https://github.com/H-uru/Plasma/pull/1127) only

Right, guess ill test and see how badly they interact.

**Comment by Hazado** [comment]
Tested the relto kickables on minkata, and wow could hardly kick the logs or rocks at all.
So yeah, not going to work with the OU codebase at all. 🤷 oh well.

**Comment by Hoikas** [comment]
I don't really see the impact on obsolete clients as being any kind of blocker to merging this if it's an improvement on our end.

**Comment by Hazado** [comment]
> I don't really see the impact on obsolete clients as being any kind of blocker to merging this if it's an improvement on our end.

I dont either, just annoying to have divergent prps

**Comment by DamnBriggsy** [comment]
> I dont either, just annoying to have divergent prps

The good news here is that these changes have done almost nothing. Save for the minor changes to friction on the cone objects, altering the mass had no impact. Any changes I felt during testing were all in my head! Per Hoikas,
>It looks like the force mode I'm using ignores the kickable mass

My suggestion is to roll back these changes completely, try to adjust the model with the original weights in mind, and make tweaks from there if necessary.

**Comment by ZarothYe** [comment]
> In light of the adjustments to [H-uru/Plasma#1127](https://github.com/H-uru/Plasma/pull/1127) in [H-uru/Plasma@9743d56](https://github.com/H-uru/Plasma/commit/9743d56b0e6689fefda3211d16a349c28c82c377), should this be closed?

I have no problem closing this. I haven't really "kicked the tires", so to speak, on TrollLand to see how that has changed things, but it doesn't seem like the weights will be making a difference at this point once some manner of PhysX 4.X is implemented, is that right? I think it's ultimately @DamnBriggsy's call, though.

**Comment by DamnBriggsy** [comment]
I agree that this should be closed.

**Pull request closed without merging**
