### PR TITLE
Q1 2023 clothing additions and changes

### PR DESCRIPTION
**Pull request by Hazado**
Bug fix for longsleeve shirts disappearing at long range from player

Guild of Instructors Short Sleeve shirt had the texture redone to better show text on back.

All new items are currently hidden by default - a pickup mechanism is to be
added later.

**TCT clothing items**
New clothing items include male and female:
- Long sleeve shirt: [M|F]Torso_LongSleeve_TCT
- Short sleeve shirt: [M|F]Torso_ShortSleeve_TCT
- Hooded sweatshirt: [M|F]Torso_SweatTCT
- Fleece pullover: [M|F]Torso_FleeceTCT

Co-authored-by: Patrick "Maurus" Mauro <patrick@patrickmauro.net>
Co-authored-by: Tim "Miles" Keller <timkeller@gmail.com>

**Mystitech clothing Items**
New clothing items include male and female:
- Long sleeve shirt: [M|F]HoodLS_MTP
- Short sleeve shirt: [M|F]Hood_MTP
- Hooded sweatshirt: [M|F]MHoodSweat_MTP

Co-authored-by: Korovev
Co-authored-by: Larry LeDeay <lwf58@hotmail.com>

**Swimtrunks clothing item**
New Clothing items include male and female:
- Shorts : [M|F]Legs_Shorts_TransDye

Co-authored-by: Traveler263 <87665301+Traveler263@users.noreply.github.com>

### CODE REVIEW

**Comment by Hazado** [comment]
Mystitech clothing items
Preview was done by Korovev in OU Discord
MTPshirt

**Comment by Hoikas** [comment]
Are these items on MOULa yet?

**Comment by Hazado** [comment]
> Are these items on MOULa yet?

No they have not made it to MOULa yet. I think March sometime

**Comment by Hazado** [comment]
Added a fix for the KI Light Sprite being visible in first person

Added the Mysterium 2023 Short sleeve shirt
Added the Kalamee Shirt

**Pull request merged**
