### PR TITLE
Fixes for Ercana Canyon

### PR DESCRIPTION
**Pull request by Hazado**
This is a collection of graphical fixes to Er'cana age.
All prps were resaved to fix any graphic issues due to textures locs possibly changing.

Canyon
Harvester cable next to ladder attached to nothing
Floating rocks and bushes under car ramp
Harvester call button floats
Spout on harvester clips through wings when harvester is moving away and cart is inside facility
See through area on harvester console
Journey cloth beside the harvester was floating
Z-flighting rocks near sinkhole and end of the line
Large Plants floating

Tunnel
Lights at top of car ramp have no view face modifier
All the lights in left tunnel are in wrong spot
2 top lights in right tunnel are gone
See out into world in between cart tunnels walkways
        
PlantExterior01
Water Tunnel doors need collisions when open

### CODE REVIEW

**Comment by Hoikas** [comment]
I know you chronicled progress on discord, but could you paste in some screenshots alongside your fix notes?

**Comment by Hazado** [comment]
Harvester Cable
image
after
image

Floating rocks and bushes under cart ramp
image
after
image

Harvester Cart Call Button floating 
image
after
image

See through area on harvester console fixed
image
after
image

Spout on harvester clips through wings when harvester is moving away and cart is inside facility
https://www.youtube.com/watch?v=Q-f1zBLc7Wo
First half of the video is the solution I used.
Second half was another way to fix this that was decided against.

Journey Cloth
image
after
image

Z-flighting rocks near sinkhole and end of the line
image
image

Large plants floating
image
image
image
image
After
image
image
image
image

View face modifiers added to lights at top of tunnel
image
after
image

Tunnel lights fixed
image
image
after
image
image

2 Lights in right tunnel added
image
after
image

See out into world in between cart tunnels walkways
image
after
image

**Comment by EhrenCG** [comment]
VanishingLights
These things always stood out to me since I play in first person a lot, round light fixtures that only appear when you are looking very close, both silos have this issue, you have to cheat to get close enough to see the light fixtures at all in the silo that you can't ride the car in.

**Comment by Hazado** [comment]
> These things always stood out to me since I play in first person a lot, round light fixtures that only appear when you are looking very close, both silos have this issue, you have to cheat to get close enough to see the light fixtures at all in the silo that you can't ride the car in.

I did notice those but i wasn't able to figure out why they vanished in the first place.

**Review by Hoikas — CHANGES_REQUESTED** [review]
Please strip off the commit 73dd274d0c49d86d1a0c7019f1a4d9474827a77f. Since you did not actually edit the Textures PRP, the cross-page references remain intact. The latest H'uru client revision does not find any problems with the references, either.

**Comment by Hazado** [comment]
Okay, ive removed the commit.

**Review by Hoikas — APPROVED** [review]

**Comment by Hoikas** [comment]
As these are largely non-controversial visual fixes, I am merging this now.

**Pull request merged**
